theme: jekyll-theme-primer
title: ""
description: "Personal website of Mathieu Stiénon"
baseurl: "" # Keep empty if using <username>.github.io; set to "/repository-name" for project pages
kramdown:
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true