theme: jekyll-theme-primer
title: ""
description: "Personal website of Mathieu Stiénon"
baseurl: "" # Keep empty if using <username>.github.io; set to "/repository-name" for project pages
kramdown:
  input: GFM
  math_engine: mathjax
  parse_block_html: true